### ISSUE TITLE
Targets list is incomplete?

### ISSUE THREAD

**Issue by mbonness** [astrowonk/TwitterWordle#1]
Just a heads up - the solution from today's puzzle (wordle #646) does not appear to be in the targets .txt file.  I noticed it when my Wordle bot failed to guess the solution today.  Since I pulled the dictionary from this project thought I would let you know.  Have a good day.

**Comment by mbonness** [comment]
Apparently the NY Times is adding words to the solutions.txt file now since today's puzzle word does not exist here either:

https://static.nytimes.com/newsgraphics/2022/01/25/wordle-solver/assets/solutions.txt

**Comment by astrowonk** [comment]
@mbonness Thanks for the info. Yeah, apparently today marks the first time the wordle solution deviated from the original list. It used to be the answer list was in order and every day the code just used the next one. Now they have an API that returns todays solution, they must have finally used that to deviate from the older order.

https://www.techradar.com/news/todays-wordle-marks-the-start-of-a-new-era-for-the-game-heres-why

It's unclear if there is any comprehensive list of possible solutions anymore. The solution to 646 is in the larger ~12K plus allowable guess list, but that contains a lot of obscure words as well.

**Comment by astrowonk** [comment]
Re: the API that tells you the solution you can see how I access it here in my [wordle solver bot code](https://github.com/astrowonk/wordle/blob/f396f25c288144bd4ce9a8a4748f438d0d608a30/tweet_script.py#L55).

**Comment by mbonness** [comment]
Thanks for all the great info.  Just to close the loop on this, I am now using a modified version of the ~12k list that contains the 646 solution and about 1,000 other words that seemed like recognizable English words.  We'll see how well it does on tomorrow's upcoming surprise word.  Here is my ~3k curated dictionary for reference:

https://github.com/mbonness/AutoWordle/blob/main/wordle-all_curated.txt

**Comment by mbonness** [comment]
Also, I should mention the solutions.txt file hosted on nytimes.com that contained the ~2k word list has been completely gutted after I complained to the Wordle editor.  So if anyone else was using that list, it's my fault. 😆
